### ISSUE TITLE
Google Places API Web Service 연동

### ISSUE THREAD

**Issue by star3058** [take-four/the_moment_server#34]
https://developers.google.com/places/web-service/get-api-key?authuser=1&hl=ko

**Comment by star3058** [comment]
### Spring에서 RestTemplate을 사용하여 REST 기반 서비스 요청

#### Generate Url 참고 코드
```java
private URI generateUrl(MultiValueMap<String, String> params) {
		return UriComponentsBuilder.fromHttpUrl(BASE_URL)
			.queryParams(params)
			.build()
			.encode()
			.toUri();
	}
```

**Comment by star3058** [comment]
1. 위도 경도로 city 알아내기
2. city 이름 + point of interset 쿼리로 (textsearch) 관광지(sightseeing) 정보 검색하기
3. db에 어떻게 저장할지

**Comment by mjmj93** [comment]
## case 1. moment 저장
1. 위도 경도로 역 geocoding (geocoding api) country and city name을 알아냄
2. 1번값을 city table에 저장 단 city 테이블에 없는경우에 새로저장
3. city name+point of interest, rankbydistance 로 쿼리 날림 (google place api 중 nearbysearch)
4. place table에 유저가 선택한 place 이름과 city id 를 저장.

## case 2. feed 조회
1. 위도 경도로 역 geocoding (geocoding api) country and city name을 알아냄
2. city name+point of interest, rankbydistance로 쿼리 날림 (google place api 중 nearbysearch)
3. 넘어온 순서대로 우리 디비에있는 moment table에 조회 (paging 처리)

**Comment by mjmj93** [comment]
## Geocoding

지역 편중
지오코딩 응답에서, Google Maps Geocoding API는 요청을 보낸 지역(일반적으로 국가)의 영향을 받은 주소 결과를 반환합니다. 예를 들어, 요청이 스페인의 도메인에서 보낸 것이 아니라 미국의 도메인에서 보낸 경우, "샌프란시스코"를 검색하면 다른 결과가 반환될 수도 있습니다.

region 매개변수를 사용하여 특정 지역으로 편중된 결과를 반환하도록 Google Maps Geocoding API를 설정할 수 있습니다. 이 매개변수는 ccTLD(국가 코드 최상위 도메인) 인수를 통해 지역 편중을 지정합니다. 대부분의 ccTLD 코드는 ISO 3166-1 코드와 동일하며, 몇몇 눈에 띄는 예외가 있습니다. 예를 들어, 영국의 ccTLD는 "uk"(.co.uk)인 반면 ISO 3166-1 코드는 "gb"입니다(기술적으로 Great Britain과 Northern Ireland 연방국" 엔터티).

주요 Google 지도 애플리케이션이 공식적으로 출시되는 모든 도메인에 대해 지오코딩 결과가 편중될 수 있습니다. 참고로, 편중은 특정 도메인의 결과를 선호할 뿐이며, 더 많은 관련 결과가 도메인 밖에 있으면 이러한 결과도 포함될 수 있습니다.

예를 들어, Google Maps Geocoding API의 기본 도메인이 미국으로 설정되어 있기 때문에, "톨레도"에 대한 지오코드는 이 결과를 반환합니다. 요청:

https://maps.googleapis.com/maps/api/geocode/json?address=Toledo&key=YOUR_API_KEY

**Comment by star3058** [comment]
<img width="1058" alt="2018-01-14 5 52 27" src="https://user-images.githubusercontent.com/5986086/34914329-df40405a-f953-11e7-9ce3-e9cefafa3b9f.png">
어떤 데이터를 받아올지, 일단 name과 type 정도만
